srcdir   = .
CMP      = cmp
RM       = rm
TR       = tr
SED      = sed
elide_cr = $(SED) "s/\r//g"

ALL: 8bit amp-escape help

8bit:
	$(SED) -f $(srcdir)/$@.sed \
		< $(srcdir)/$@.inp | $(elide_cr) > $@.out
	$(CMP) $(srcdir)/$@.good $@.out
	$(RM) $@.out

amp-escape:
	$(SED) -f $(srcdir)/$@.sed \
		< $(srcdir)/$@.inp | $(elide_cr) > $@.out
	$(CMP) $(srcdir)/$@.good $@.out
	$(RM) $@.out

help:
	$(SED) --help | $(SED) "1s/ [^ ]* / sed /" > $@.1out
	$(SED) 2>&1 | $(SED) "1s/ [^ ]* / sed /" > $@.2out || :
	$(CMP) $@.1out $@.2out 
	$(RM) $@.1out $@.2out
